# Enable new collation to make case-insensitive comparison work.
new_collations_enabled_on_first_bootstrap = true

# Disable async-commit to make DDL run faster.
[tikv-client.async-commit]
safe-window = 0
allowed-clock-drift = 0
